on: [push]
name: Lint and Test
jobs:
  full-run:
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.39
        skip-build-cache: true
        skip-pkg-cache: true
        skip-go-installation: true
    - name: Test
      run: go test -v ./...